# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InlineModel1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='InlineModel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MasterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='inlinemodel2',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.MasterModel'),
        ),
        migrations.AddField(
            model_name='inlinemodel1',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.MasterModel'),
        ),
    ]
