# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastermodel',
            name='test1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.MasterModel'),
        ),
        migrations.AlterField(
            model_name='mastermodel',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
